language: rust

cache:
  cargo: true
  apt: true

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

rust:
  - stable
  - beta
  - nightly

jobs:
  allow_failures:
    - rust: nightly

before_script:
  - export PATH="${PATH}:${HOME}/.cargo/bin"

script:
  - |
      cargo build --verbose --all-features;
      travis_wait 30 cargo test;
      if [ "${TRAVIS_RUST_VERSION}" == 'nightly' ]; then
        cargo bench --verbose --no-run --all-features;
      fi
      cargo doc --verbose;
