[package]
name = "poisson-visualisation"
version = "0.1.0"
authors = ["WaDelma <>"]
edition = "2018"

[dependencies]
glam = "0.9"
image = "0.23"
clap = "2"
rand = "0.7"
lab = "0.8"
fnv = "1"
poisson2d = { path = "../poisson2d" }